name: BK-test
favicon: null
layout_spectrum: 0.9679579942021519
typography_spectrum: 0.6089956804644316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4086690859403461
  lightness: 0.6302249860018492
  saturation: 0.09670096915215254
  rhythmicContrast: 0.08248038589954376
purpose: []
