name: BK-test
favicon: null
layout_spectrum: 0.25723
typography_spectrum: 0.39677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf8'
    - '#000000'
    - '#4166d9'
    - '#72b8f0'
    - '#273f74'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
